### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by headius** [ruby/io-console#10]
JRuby needs a -java platform version of io-console.

We have partial support for the io/console library currently, but not in gem form. Moving our code to a gem would not be difficult. We would maintain the code in this repository, but pushes of new releases would need to happen for both standard and -java gems (pushing only the standard one would break JRuby).

The JRuby code is pure-Ruby, using FFI where necessary: https://github.com/jruby/jruby/tree/master/lib/ruby/stdlib/io

**Comment by headius** [comment]
I ran into this today because reline started to depend on the io-console gem. See jruby/jruby#5802 and jruby/jruby#5803. We will be unable to use reline on JRuby until there's a JRuby-compatible io-console release.

**Comment by eregon** [comment]
Ref https://github.com/ruby/reline/issues/124 and https://github.com/oracle/truffleruby/issues/1904#issuecomment-585147711

**Comment by eregon** [comment]
I think https://github.com/ruby/reline/pull/125 unblocks the immediate problem for `reline`, but of course we should still do this.

I'll also try a bit to see what it'd take to get either the FFI or C extension version working on TruffleRuby to pass the tests.

**Comment by headius** [comment]
io-console still appears to try to build the extension on JRuby when running on Windows:

```
C:\Users\headius\work\jruby>bin\jruby -S gem install io-console
Fetching io-console-0.5.6.gem
Building native extensions. This could take a while...
C:/Users/headius/work/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:76: warning: unsupported popen option: err
ERROR:  Error installing io-console:
        ERROR: Failed to build gem native extension.

    current directory: C:/Users/headius/work/jruby/lib/ruby/gems/shared/gems/io-console-0.5.6/ext/io/console
C:/Users/headius/work/jruby/bin/jruby.exe -I C:/Users/headius/work/jruby/lib/ruby/stdlib -r ./siteconf20201222-6880-fawjb1.rb extconf.rb

current directory: C:/Users/headius/work/jruby/lib/ruby/gems/shared/gems/io-console-0.5.6/ext/io/console
make "DESTDIR=" clean
current directory: C:/Users/headius/work/jruby/lib/ruby/gems/shared/gems/io-console-0.5.6/ext/io/console
make "DESTDIR="
make failedCannot run program "make" (in directory "C:\Users\headius\work\jruby\lib\ruby\gems\shared\gems\io-console-0.5.6\ext\io\console"): CreateProcess error=2, The system cannot find the file specified

Gem files will remain installed in C:/Users/headius/work/jruby/lib/ruby/gems/shared/gems/io-console-0.5.6 for inspection.
Results logged to C:/Users/headius/work/jruby/lib/ruby/gems/shared/extensions/universal-java-1.8/2.5.0/io-console-0.5.6/gem_make.out
```

I believe it was modified to no-op the extension build on JRuby, but why isn't that happening here?

**Comment by headius** [comment]
Ah yes... the hack of making a no-op makefile is not sufficient for JRuby because `make` will still not be present (JRuby never requires build tools on a host system).

The change in 41b6f095745758f979e72bd83518ad6e8cbe2419 is not sufficient to prevent the system from attempting to run `make`.

**Comment by headius** [comment]
This gem blocks the adoption of reline (and new irb) because the io-console gem cannot be installed by JRuby on Windows.

https://github.com/jruby/jruby/pull/5803

I will revisit getting the FFI version into this gem for platforms that do not support building native extensions.

**Comment by eregon** [comment]
A short update:

> I'll also try a bit to see what it'd take to get either the FFI or C extension version working on TruffleRuby to pass the tests.

@aardvark179 tried both the FFI and C extension backends for `io-console`, and they both seem to work.
We decided for now to go with the C extension for maximum compatibility.

This means once that's merged we should make a PR to change https://github.com/ruby/io-console/blob/83370287afa407eec00b993a4f91882592ca0b89/ext/io/console/extconf.rb#L4 so the extension is also compiled on TruffleRuby, if >= some TruffleRuby release.
Probably should be a similar check to what's in FFI: https://github.com/ffi/ffi/blob/b79f52536af71fd05c78931f5162be83b1820c3a/lib/ffi.rb#L15 (that also includes dev builds before the release, which is convenient)

**Comment by nobu** [comment]
> Ah yes... the hack of making a no-op makefile is not sufficient for JRuby because `make` will still not be present (JRuby never requires build tools on a host system).

It is an issue outside/before extconf.rb.
Won't `gem install io-console --platform=java` install `io-console-x.y.z-java.gem`?

**Comment by headius** [comment]
> It is an issue outside/before extconf.rb

I am not sure what you mean. In my most recent output you can see it gets to the point of invoking `make` but cannot because it does not exist. Generating a dummy makefile will skip the extension build but still requires that `make` be available.

> Won't gem install io-console --platform=java install io-console-x.y.z-java.gem?

Yes, once there is a `java` version of the io-console gem it would install that gem.

This may be the only way to make sure the gem is installable without `make` being present. I do not know of any way to make extension building fully switchable by platform in a single gem.

**Comment by headius** [comment]
> @aardvark179 tried both the FFI and C extension backends for io-console, and they both seem to work.

Yes, I have been chatting with him about it. I hope to see a PR on my fork with any fixes he needed to make and I will incorporate that into my PR for the gem.

**Comment by nobu** [comment]
> > It is an issue outside/before extconf.rb
> 
> I am not sure what you mean. In my most recent output you can see it gets to the point of invoking `make` but cannot because it does not exist. Generating a dummy makefile will skip the extension build but still requires that `make` be available.

As extconf.rb itself doesn't invoke `make`, it is typically `ruby extconf.rb && make`.
I meant "outside" in this sense.

**Comment by headius** [comment]
> As extconf.rb itself doesn't invoke make, it is typically ruby extconf.rb && make.

Ok I understand. Yes, I believe the call of `make` is done by RubyGems extension building logic.

I did not mean to imply there was anything wrong with extconf or the dummy Makefile, but that change not enough to let the gem install without `make` available.
