### ISSUE TITLE
TruffleRuby v20.1.0 doesn't patch StringIO

### ISSUE THREAD

**Issue by piotrmurach** [ruby/io-console#14]
Using MRI Ruby and JRuby loading `"io/console"` extends `StringIO` with extra methods. 

For example:

```ruby
require "stringio"
sio = StringIO.new
sio.respond_to?(:getch) # => false
```
then loading `"io/console"` adds `getch` support:

```ruby
require "io/console"
sio.respond_to?(:getch) # => true
```

With TruffleRuby, that's not the case:

```ruby
require "io/console"
sio.respond_to?(:getch) # => false
```
I'm using TruffleRuby `v20.1.0` locally and the failure is also happening in the [Travis CI](https://travis-ci.org/github/piotrmurach/tty-pager/jobs/692615486)

Hopefully, this helps to identify the issue and apologies if this is already fixed.

/cc @eregon @bjfish @chrisseaton

**Comment by eregon** [comment]
Thanks for the report.
Currently TruffleRuby and JRuby use a separate implementation for io/console than this gem (#10/#11).

It looks like JRuby has that behavior with
https://github.com/jruby/jruby/blob/9.2.8.0/lib/ruby/stdlib/io/console/common.rb#L23-L34
I'll copy that logic over to TruffleRuby.

The C extension OTOH does this with a hidden (lowercase!) constant in
https://github.com/ruby/io-console/blob/2b8ba023c8d058388827d97ce267a28dd7b97324/ext/io/console/console.c#L1646

Which looks funny for:
```
$ ruby -rstringio -e 'p StringIO.ancestors'
[StringIO, IO::generic_writable, IO::generic_readable, Enumerable, Data, Object, Kernel, BasicObject]
```

TruffleRuby doesn't support yet such constants, and it's actually the first error with:
```
$ chruby truffleruby-dev
$ gem i io-console:0.5.5
$ ruby -rio/console.so -e0                             
/home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1081:in `const_defined?': wrong constant name generic_readable (NameError)
	from /home/eregon/.rubies/truffleruby-dev/lib/truffle/truffle/cext.rb:1081:in `rb_define_module_under'
	from define.c:26:in `rb_define_module_under'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/io-console-0.5.5/ext/io/console/console.c:1637:in `InitVM_console'
```

**Comment by eregon** [comment]
Fixed in https://github.com/oracle/truffleruby/commit/75b6f5ffadca79aff314ce9887fdfb6c23a1ad1d, thanks for the report.
