### ISSUE TITLE
Release 0.5.10 to RubyGems?

### ISSUE THREAD

**Issue by mensfeld** [ruby/io-console#30]
Ruby 3.1.0 ships with io-console version 0.5.10. It is however missing in RubyGems. Would there be a chance to have it released there? https://rubygems.org/gems/io-console

**Comment by nobu** [comment]
We’d release 0.5.11 instead, in the near future.

**Comment by nijikon** [comment]
https://my.diffend.io/gems/io-console/0.5.9/0.5.11 was released. We can close this issue.

**Comment by mensfeld** [comment]
Great. Thank you @nobu
